### ISSUE TITLE
Just saw this and it made me smile

### ISSUE THREAD

**Issue by fractaledmind** [deanishe/zothero#1]
Just wanted to say that this workflow looks awesome, and it put a smile on my face to think that academics out there will have such an awesome way to work with their citations. I've been out of the Alfred Workflow game for a long time now, but I still respect the hell out of you. And it is cool to see you bring your skills and elegant code to Zotero.

**Comment by deanishe** [comment]
Thanks.

We tried to get a fork of ZotQuery up and running, but I couldn't really figure out the code. I think I might have been looking at the wrong version 😞 

I built this slimmed down version with the goal of creating something maintainable for somebody else to take over: I've never cited anything in my life.

**Comment by fractaledmind** [comment]
That's a great idea. I'll put that link in tonight.

And yeah, the ZotQuery codebase is in a bad state, as I stopped working on it in the middle of a rewrite.

I'm a webapp developer now in Philadelphia (note: I write Ruby on Rails code, not React code 😉).

I actually just got promoted to Senior Web Developer this week. It's kinda crazy to look back and recall that 3 years ago I was in a PhD program just trying to learn enough Python, SQL, code organization best practices, etc. to build tools to help me be a student. And now I do this full-time. I can honestly say I wouldn't be in this position (which makes me so much happier than I was in grad school) without working with you back in the day. Thanks a ton for giving me the time and space to slowly learn so much from you. On this side of things, I see so much more clearly how generous and gracious that was on your part. Thank you so much!

**Comment by fractaledmind** [comment]
The link from the ZotQuery README to this repo is now in place.

**Comment by deanishe** [comment]
That's extremely kind of you. I'm glad you're doing well and enjoying it!

If you ever need a Python or Go contractor, let me know 😉

**Comment by deanishe** [comment]
Have a good Chrimbo and New Year 🎉
