### ISSUE TITLE
Markdown/pandoc support

### ISSUE THREAD

**Issue by tormodb** [deanishe/zothero#10]
Thanks for this fantastic workflow!

I was wondering whether you would consider adding support for pandoc/markdown style citatations. This way, in addition to copying 'citation' and 'bibliography', there would be an option to copy the 'Citation key' (preferably prefixed by an "@").

There is a different workflow implementing something similar for Bibdesk (https://www.zvi-biener.org/tech-blog/searching-bibdesk-with-alfred), if it is not clear by my description what I am requesting.

Best regards, 
Tormod Bøe

**Comment by deanishe** [comment]
I don't know Bibdesk, and I don't really understand what you're asking for.

What is a "citation key" and where would I find one in Zotero?

The formatting is done using CSL styles. You might want something like [this](https://github.com/philipbelesky/Markdown-Citation-Style-Languages).

**Comment by tormodb** [comment]
OK, thanks for responding. 

FYI a citation key is a unique identifier that links a citation with it's reference, and is what pandoc/latex uses for citations. By inserting the cite key in a manuscript, pandoc/latex looks it up in a library of references/a bibtex file and inserts a fully formatted reference into a manuscript. 

I have since read that this key is actually stored independently from the zotero library in a database maintained by the zotero better bibtex plugin, and from reading a different post, I got the understanding that these keys are not available for a workflow such as yours.

Thanks, 
Tormod

**Comment by deanishe** [comment]
> I have since read that this key is actually stored independently from the zotero library in a database maintained by the zotero better bibtex plugin, and from reading a different post, I got the understanding that these keys are not available for a workflow such as yours.

That's the important bit.

I'm not familiar with the plugin, but the best-case scenario would be additional parsing logic to find and load the plugin's data (a JSON file, I think), and a rewrite of the citation-generation system, as it's built around the assumption that all citations are generated by `citeproc-js` from CSL styles.

That's quite a lot of work to support a plugin, and I'm reluctant to do it unless Better Bibtex is a very common plugin.

**Comment by robsalasco** [comment]
+1 pandoc support would be very nice

**Comment by Rupertofly** [comment]
would also appreciate it very much

**Comment by deanishe** [comment]
> but lacking Better Bibtex support makes it less useful in my daily work

Feel free to add the feature and submit a pull request.

**Comment by januz** [comment]
Would code from this workflow be useful? https://github.com/alanzchen/zotero-better-bibtex-alfred

Thanks for your work on Zothero, it's amazing, as the others I'm just missing access to citekeys...

**Comment by deanishe** [comment]
> Would code from this workflow be useful?

Afraid not. That workflow works in a fundamentally different way to this one.

**Comment by nomaad** [comment]
Instead of adding support for the plugin, could it be a workaround to create a CSL that generates citekeys (or tweak that one: https://github.com/citation-style-language/styles/blob/master/bibtex.csl)?
