### ISSUE TITLE
Remove Alfred dependency (cross platform)

### ISSUE THREAD

**Issue by gagarine** [deanishe/zothero#12]
Very good job with Zothero! I would love to see a similar tools replacing the default Zotero picker.

How hard would it be to to not use Alfred and make a cross platform selector? I read your Python code, as I understand Alfred is "only" used for the UX.

Also I'm not sure that directly connecting to the DB is the best way. Instead it's possible to use the Zotero API to query the library (but then the Zotero need to be launched).

I'm think of somethings like http://support.readcube.com/support/solutions/articles/30000024001-magic-citations-on-papers-3-for-mac

<img width="436" alt="citations - select first author" src="https://user-images.githubusercontent.com/164074/39042801-1343b822-448c-11e8-967f-bd956a189112.png">

The papers 3's magic citation is not only limited to cite, but can also transform the citekey in citation (in any text editor).
<img width="1263" alt="citations - format manuscript" src="https://user-images.githubusercontent.com/164074/39043101-d14f99c6-448c-11e8-887f-9de347c3a52a.png">

**Comment by deanishe** [comment]
> calling directly Sqlite is perhaps easier than using an undocumented API ;)

Especially as I've already written that one!

**Comment by gagarine** [comment]
OK, I keep that in mind has a potential summer project. Writing a front end in QT should not be that hard (it's basically a drop-down list).

**Comment by deanishe** [comment]
Bear in mind that the only targeted platform is macOS-native Python, i.e. 2.7.

I didn't consider Py3 for a single second while writing the code. The API is Unicode, of course, but I haven't got a clue about Py3 compatibility.

Anyhoo, I'll close this issue, but please feel free to post further comments.
