### ISSUE TITLE
AppKit Dependency

### ISSUE THREAD

**Issue by gustybear** [deanishe/zothero#13]
The pasteboard relies on AppKit, which is bundled with Xcode. I tried install PyobjC with the homebrew version of python. But Alfred clears my PATH variable before running the workflow, which ignore the third party python and its modules.

`
20:26:57 workflow.py:2074 ERROR    No module named AppKit
Traceback (most recent call last):
  File "./lib/workflow/workflow.py", line 2067, in run
    func(self)
  File "./zh", line 613, in main
    return do_copy(args['<style>'], entry_id, args['--bibliography'])
  File "./zh", line 302, in do_copy
    import pasteboard as pb
  File "./lib/pasteboard.py", line 14, in <module>
    from AppKit import NSPasteboard
ImportError: No module named AppKit
`

**Comment by deanishe** [comment]
AFAIK, PyObjC has been included with the default macOS Python since Leopard. You only need Xcode if you want to install (build) your own copy.

Alfred doesn't clear your PATH. macOS applications are not launched from your shell.

**Comment by gustybear** [comment]
I managed to install PyObjC to the system python. Somehow mine does not have PyObjC installed.

**Comment by deanishe** [comment]
What version of macOS are you using?

AFAIK, PyObjC is installed in all system Pythons by default. Certainly, I would have heard more complaints before now if it weren't (I use `NSPasteboard` in quite a few of my workflows).
