### ISSUE TITLE
initializing search index never finishes

### ISSUE THREAD

**Issue by tdiprete** [deanishe/zothero#15]
zothero worked fine until I installed the new update.   Now it gives the "initializing search index" message whenever I try a search and it never gets past this message.  I tried putting the explicit path to my zotero data (I used the default, but in any case), but that didn't solve the problem.

**Comment by deanishe** [comment]
You could start by trying `zot workflow:delcache` to clear the cache.

If that doesn't work, please enter `zot workflow:openlog` to open the logfile and post its contents here. The actual problem should be logged in there.

**Comment by tdiprete** [comment]
Thanks. That didn’t work and I’ve attached the log file.
Tom

**Comment by deanishe** [comment]
Where's the log file? Are you replying by email? I don't think attachments work.

**Comment by tdiprete** [comment]
I attached it to the email.  I'll put it directly into the github thread.

**Comment by tdiprete** [comment]
here's the log file.
[net.deanishe.alfred.zothero.log](https://github.com/deanishe/zothero/files/2186015/net.deanishe.alfred.zothero.log)

**Comment by deanishe** [comment]
Thanks. I can't replicate the problem, but I think I've fixed it all the same.

Try updating to [v1.0.1](https://github.com/deanishe/zothero/tree/v1.0.1) (You can update via Alfred with `zot workflow:update`)

**Comment by deanishe** [comment]
You're not using the latest version or you've posted the wrong logfile. The error is not from the lastest version of the workflow:

```
  File "./lib/zothero/index.py", line 346, in _update
    if hostname.startswith('www.'):
```

But line [346 of the current workflow](https://github.com/deanishe/zothero/blob/4e4fc92b673a96d220dca66519467c2f93808556/src/lib/zothero/index.py#L346) is:

```
if not hostname:
```

Please ensure you're really using the latest version.

**Comment by tdiprete** [comment]
I had installed it, but maybe I had to quit and restart.  Now it is working.  Thanks for the fix.
