### ISSUE TITLE
Citations for caselaw

### ISSUE THREAD

**Issue by GPadraic** [deanishe/zothero#16]
The workflow doesn't seem to be querying case names. For example, querying a case titled Doe v. Snyder, I get the following

![image](https://user-images.githubusercontent.com/42655629/44548997-b477a500-a6ed-11e8-9a92-11ce633d3522.png)

Works great for journal articles, and if I could figure out how to get it to play nice with caselaw that would be stellar

**Comment by deanishe** [comment]
"Case name" isn't a field I'm familiar with. Could you upload a sample library with some case names somewhere, so I can have a look for myself?

**Comment by GPadraic** [comment]
I would if I could figure out how to do that -- I would just upload my library except it is quite large. Perhaps this would be easier -- in vanilla zotero, if you add a new item and select case, case name is the second field in the info pane. If you need a sample library, are there instructions somewhere for compiling one? Thank you, and thank you for this workflow. It works perfectly with my secondary research

**Comment by deanishe** [comment]
I've found the case name, but I can't implement this because I have no idea how to cite a case.

**Comment by deanishe** [comment]
Closing this issue. I don't know how to do it, and apparently nobody cares enough about the feature to bother explaining it to me.
