### ISSUE TITLE
Question - any way to insert full bibliography?

### ISSUE THREAD

**Issue by Honoluluskye** [deanishe/zothero#18]
Hi! Sorry if this is a dumb question but wondering if there's anyway to generate a full bibliography that compiles all of the individual references that I've inserted into a scrivener file? Thanks!

**Comment by deanishe** [comment]
I'm afraid not. The workflow just pastes stuff. It has no idea where anything goes to.

Even if it had a memory of what it pasted where, it wouldn't be a reliable list of references unless you never inserted a reference any other way and never deleted a reference it had inserted from your document.

Generally speaking, to get an accurate list of the references in a document (which appears to be what you're asking), you need to read the actual document or integrate with an application that can, and that's well outside the scope of a simple workflow.
