### ISSUE TITLE
Expand the copy citation to "Quick Copy"

### ISSUE THREAD

**Issue by specter119** [deanishe/zothero#20]
the open issues are mostly related to the markdown citation.

It seems that ZotHero get citation/bibliography from [cpjs](https://github.com/Juris-M/citeproc-js).
but Zotero also has a build in function called "Quick Copy", it contains "Export" formats and the "Citation Style" formats.

the "Export" formats contains more such like BetterBibTex citation key, json, csv and so on. which is more broad than CSL export. what's more, it is easily customized, for example <https://zoteromusings.wordpress.com/2013/04/23/zotero-item-uris-from-client/>.

Quick Copy will directly return bibliography if I choose csl style, I also think copy the citations of csl will be less useful than citation-key.

So, I think remain the bibliography function as it is and expand the citation export to "Quick Copy" will be better.

**Comment by deanishe** [comment]
> Zotero also has a build in function called "Quick Copy", it contains "Export" formats and the "Citation Style" formats.

Do you know how an external program can access this internal function?

**Comment by specter119** [comment]
I don't know yet, I will find if some api can do this later.
