### ISSUE TITLE
How to copy the bibliography?

### ISSUE THREAD

**Issue by bl0** [deanishe/zothero#28]
Hi, thanks for the amazing workflow.

I often write paper in Latex format, so it will be much better if I can copy the bibliography from the workflows. But I can't find any way in the README.

Do you have any way to do this? Thanks very much.

**Comment by deanishe** [comment]
I'm afraid the workflow doesn't know anything about bibliographies. It only understands individual entries.

**Comment by bl0** [comment]
Maybe my description is not accurate. I mean, can I copy the BibTeX of an entry? Which can be done by `Export item` in the Zotero app.

**Comment by bl0** [comment]
![image](https://user-images.githubusercontent.com/9164121/67265972-a6840680-f4e1-11e9-9fb3-88c21caecce6.png)

**Comment by deanishe** [comment]
> I mean, can I copy the BibTeX of an entry?

Set your citation style to BibTex, and use <kbd>⌥↩</kbd> to copy a bibliography style citation.

**Comment by bl0** [comment]
No no no, the results of ⌥↩ is something like:
```
[1]	Z. Wu, Y. Xiong, S. X. Yu, and D. Lin, “Unsupervised Feature Learning via Non-Parametric Instance Discrimination.,” CVPR, pp. 3733–3742, Jan. 2018.
```

But what I want to copy something like:

```bibtex
@article{zagoruyko2016wide,
  title={Wide residual networks},
  author={Zagoruyko, Sergey and Komodakis, Nikos},
  journal={arXiv preprint arXiv:1605.07146},
  year={2016}
}
```

**Comment by deanishe** [comment]
> No no no

Yes, yes, yes

![bibtex](https://user-images.githubusercontent.com/747913/67281059-e5f52780-f4ce-11e9-846c-b9b2ca7a0783.gif)

**Comment by bl0** [comment]
Thanks very much. What I need is the `BibTeX generic citation style`.

**Comment by LouisonGitzinger** [comment]
Hi there, how can I choose my own bibliography style ?

**Comment by deanishe** [comment]
> Because changing the default citation style also change the default bibliography export.

Yes. The workflow uses a single CSL style for both. It assumes you want your citations and bibliography to match.

> I have some custom bibliography styles that I would like to use to export an article bibliography using zotHero

You can't choose different CSL styles for citations and bibliography, so you would need to create a custom CSL style that defines your preferred citation and bibliography styles.

**Comment by LouisonGitzinger** [comment]
Thank you very much for your answer, it's crystal clear now

**Comment by fredcallaway** [comment]
I am stuck at the configuration step. Bibtex doesn't show up as an option with zotconf, and if I try to manually edit CITE_STYLE to http://www.zotero.org/styles/bibtex (which does exist) I get an error: ` 'NoneType' object has no attribute 'name'`

<details>
<summary>Debug trace</summary>
[11:13:04.960] ZotHero[Script Filter] Queuing argument 'm'
[11:13:05.045] ZotHero[Script Filter] Queuing argument 'ma'
[11:13:05.155] ZotHero[Script Filter] Queuing argument 'mar'
[11:13:05.304] ZotHero[Script Filter] Queuing argument 'marr'
[11:13:05.371] ZotHero[Script Filter] Script with argv 'm' finished
[11:13:05.377] STDERR: ZotHero[Script Filter] .
11:13:05 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
11:13:05 workflow.py:1468 DEBUG    reading settings from /Users/fred/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
11:13:05 workflow.py:2343 DEBUG    update check not due
11:13:05 zh:667 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': u'm',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': True,
 'setvar': False,
 'style': False}
11:13:05 config.py:85 DEBUG    [config] datadir=u'/Users/fred/Zotero'
11:13:05 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
11:13:05 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
11:13:05 core.py:74 DEBUG    [core] attachments_dir=None
11:13:05 core.py:133 DEBUG    [core] storage=u'~/Zotero/storage'
11:13:05 core.py:134 DEBUG    [core] styles=u'~/Zotero/styles'
11:13:05 cache.py:311 DEBUG    [cache] opening store 'styles'...
11:13:05 cache.py:311 DEBUG    [cache] opening store 'modtimes'...
11:13:05 workflow.py:2080 ERROR    'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "./lib/workflow/workflow.py", line 2073, in run
    func(self)
  File "./zh", line 717, in main
    return do_search(query)
  File "./zh", line 117, in do_search
    log.debug(u'Citation style: %s', style.name)
AttributeError: 'NoneType' object has no attribute 'name'
11:13:05 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/zothero/issues
11:13:05 workflow.py:2103 DEBUG    ---------- finished in 0.111s ----------
[11:13:05.382] ZotHero[Script Filter] {"items": [{"valid": false, "subtitle": "'NoneType' object has no attribute 'name'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'ZotHero'"}]}
[11:13:05.639] ZotHero[Script Filter] Script with argv 'marr' finished
[11:13:05.654] STDERR: ZotHero[Script Filter] .
11:13:05 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
11:13:05 workflow.py:1468 DEBUG    reading settings from /Users/fred/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
11:13:05 workflow.py:2343 DEBUG    update check not due
11:13:05 zh:667 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': u'marr',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': True,
 'setvar': False,
 'style': False}
11:13:05 config.py:85 DEBUG    [config] datadir=u'/Users/fred/Zotero'
11:13:05 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
11:13:05 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
11:13:05 core.py:74 DEBUG    [core] attachments_dir=None
11:13:05 core.py:133 DEBUG    [core] storage=u'~/Zotero/storage'
11:13:05 core.py:134 DEBUG    [core] styles=u'~/Zotero/styles'
11:13:05 cache.py:311 DEBUG    [cache] opening store 'styles'...
11:13:05 cache.py:311 DEBUG    [cache] opening store 'modtimes'...
11:13:05 workflow.py:2080 ERROR    'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "./lib/workflow/workflow.py", line 2073, in run
    func(self)
  File "./zh", line 717, in main
    return do_search(query)
  File "./zh", line 117, in do_search
    log.debug(u'Citation style: %s', style.name)
AttributeError: 'NoneType' object has no attribute 'name'
11:13:05 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/zothero/issues
11:13:05 workflow.py:2103 DEBUG    ---------- finished in 0.066s ----------
[11:13:05.658] ZotHero[Script Filter] {"items": [{"valid": false, "subtitle": "'NoneType' object has no attribute 'name'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'ZotHero'"}]}
</details>

**Comment by deanishe** [comment]
> Bibtex doesn't show up as an option with zotconf, and if I try to manually edit CITE_STYLE to http://www.zotero.org/styles/bibtex (which does exist) I get an error

@fredcallaway Yeah. If you set `CITE_STYLE` to a style the workflow doesn't know about, you're going to get an error.

> which does exist

What does that mean? Exists where?

Have you tried reloading the workflow with `zotconf > "Reload Zotero Data"`?

**Comment by fredcallaway** [comment]
It "exists" in the sense that that link downloads a csl. I set the citation ctyle to apa formatting using zotconf and saw that `CITE_STYLE` was set to http://www.zotero.org/styles/apa (a link where you can download a .csl file) I figured I could switch in any other valid CSL link, but clearly not.

I tried reloading after setting CITE_STYLE to the /bibtex url. No luck. It all works fine if I go back to /apa

The real question here is this: How can I set the citationstyle to BibTeX? Based on the gif above, you were able to do it.

**Comment by deanishe** [comment]
> It "exists" in the sense that that link downloads a csl.

That isn't the appropriate sense of exist.

> The real question here is this: How can I set the citationstyle to BibTeX?

Have your tried [reading the instructions](https://github.com/deanishe/zothero#citation-styles)?

**Comment by fredcallaway** [comment]
>Have your tried reading the instructions?

Ugh, clearly not closely enough. I got it now. Sorry for wasting your time.

I still can't figure out how to export better bibtex bibliography items (as opposed to cite keys with `COPY_CITEKEY_MOD`) but it looks like that might not be possible.

**Comment by deanishe** [comment]
> Ugh, clearly not closely enough.

:D

> I still can't figure out how to export better bibtex bibliography items (as opposed to cite keys with COPY_CITEKEY_MOD) but it looks like that might not be possible.

It's not possible. The workflow has no concept of a bibliography. As soon as you've copied a citation, it instantly forgets about it.

**Comment by fredcallaway** [comment]
Oh sorry, I wasn't clear. I just meant pasting a "bibliography-style citation" in better bibtex style with `⌥↩`. Basically I would like something that looks like this:
```
@book{Marr1982Vision,  # note my cite key format
  title = {Vision: {{A}} Computational Investigation into the Human Representation and Processing of Visual Information},
  author = {Marr, David},
  year = {1982},
  publisher = {{San Francisco: WH Freeman}}
}
```

as opposed to this, which is the "BibTeX generic citation style".
```
@book{Marr_1982, title={Vision: A computational investigation into the human representation and processing of visual information}, publisher={San Francisco: WH Freeman}, author={Marr, David}, year={1982} }
```

But I think this is not possible because better bibtex isn't a CSL. Incidentally, the thing you thought I meant, keeping track of the citations you copy until you paste a bibliography for all of them would be a very neat feature indeed.

Don't worry about this though! This plugin is already excellent—thanks for your work on it, and for the excellent support as well.
