### ISSUE TITLE
Feture request: is it possible add citations in MS word?

### ISSUE THREAD

**Issue by llity** [deanishe/zothero#34]
Replace the Zotero add-ins. Thanks!
![image](https://user-images.githubusercontent.com/11771112/81502850-20130300-9313-11ea-8efc-1d38a3f7d757.png)

**Comment by deanishe** [comment]
Sorry, but that's way out of scope.

The workflow just reads Zotero's data directly from disk. It doesn't talk to the Zotero application, and it certainly doesn't talk to Word.
