### ISSUE TITLE
Back functionality to return to list of search results

### ISSUE THREAD

**Issue by pjattke** [deanishe/zothero#35]
Zothero is awesome, thanks a lot for it! The recently added feature to copy the BibTeX key is awesome and further facilitated my workflow. Thank you very much—great work!  

A feature I am still missing yet is a kind of "go back" functionality. For example, after typing `zot <name of paper>` I choose the desired paper and switch into its attachments by pressing ⇧+⌅. Usually, I then use Alfred's integrated QuickLook feature by pressing ⇧ to take a look into the PDF before opening it in my PDF viewer. Sometimes, I notice that I have chosen the wrong entry and thus want to go back to the list of search results. I could not find any way to accomplish that. Is that supported somehow, just a missing feature, or generally not intended by Alfred's workflow design?

**Comment by deanishe** [comment]
> The recently added feature to copy the BibTeX key is awesome and further facilitated my workflow. Thank you very much—great work!

Thank @yarray for the BibTeX support.

> and thus want to go back to the list of search result

Close and re-open Alfred, then press the up-arrow to recall your last query.

It's not perfect, but because Alfred doesn't have any native support for any kind of "go back" feature, it isn't going to be any easier to back up two levels with a workflow-level implementation.

**Comment by pjattke** [comment]
Alright, I see. That's what I already thought as other workflows neither have this feature. Thanks for the explanation and the tip with the "last query" function.

**Comment by deanishe** [comment]
> That's what I already thought as other workflows neither have this feature.

Yeah. I've added a "go back" feature to a few workflows that navigate deep-ish trees of data, but with a workflow like this one, it's likely that it'll get in the way as much as it will help. If I add a "Go Back" item at the top of every list, then the attachment you're interested in will *never* be selected. And if I add it to the bottom of the list, then it's not much—if any—easier to use than Alfred's own query history is.
