### ISSUE TITLE
"No matches found" for new added items

### ISSUE THREAD

**Issue by Lightmann** [deanishe/zothero#39]
ZotHero can not find some items, especially the new added items.
This is the situation even if I rebuilt the index in Zotero:  
![image](https://user-images.githubusercontent.com/32094465/84335140-c0846d80-abc6-11ea-9c50-f80a8651a71c.png)
![image](https://user-images.githubusercontent.com/32094465/84335861-74d2c380-abc8-11ea-9b84-2c312d165354.png)
![image](https://user-images.githubusercontent.com/32094465/84335907-8d42de00-abc8-11ea-8325-05668c9eb634.png)
(I changed the key from 'zot' to 'z')

**Comment by deanishe** [comment]
> This is the situation even if I rebuilt the index in Zotero

Have you tried rebuilding ZotHero's index via `zotconf` > `Reload Zotero Data`?

You should also check the log file for errors (enter `z workflow:openlog` in Alfred).

**Comment by Lightmann** [comment]
Thanks. `Reload Zotero Data` works.
